
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include themes.yaml
  
light:
  - platform: mqtt
    name: "Luce Cortile"
    command_topic: "cmnd/danieletest3199/power"
    state_topic: "cmnd/danieletest3199/power"
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: "Luce Ingresso"
    command_topic: "cmnd/danieletest3199mk2/power"
    state_topic: "cmnd/danieletest3199mk2/power"
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: "Pump Sensor"
    command_topic: "hometest/test321/test"
    state_topic: "hometest/test321/test"
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: "Luce Camera 1"
    command_topic: "cmnd/danieletest3199mk3/POWER"
    state_topic: "tele/danieletest3199mk3/STATE"
    state_value_template: "{{ value_json.POWER }}"
    availability_topic: "tele/danieletest3199mk3/LWT"
    brightness_command_topic: "cmnd/danieletest3199mk3/Dimmer"
    brightness_state_topic: "tele/danieletest3199mk3/STATE"
    brightness_scale: 100
    on_command_type: "brightness"
    brightness_value_template: "{{ value_json.Dimmer }}"
    color_temp_command_topic: "cmnd/danieletest3199mk3/CT"
    color_temp_state_topic: "tele/danieletest3199mk3/STATE"
    color_temp_value_template: "{{ value_json.CT }}"
    rgb_command_topic: "cmnd/danieletest3199mk3/Color2"
    rgb_state_topic: "tele/danieletest3199mk3/STATE"
    rgb_value_template: "{{ value_json.Color.split(',')[0:3]|join(',') }}"
    effect_command_topic: "cmnd/danieletest3199mk3/Scheme"
    effect_state_topic: "tele/danieletest3199mk3/STATE"
    effect_value_template: "{{ value_json.Scheme }}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 0
    retain: false
  - platform: mqtt
    name: "Luce Camera 2"
    command_topic: "cmnd/danieletest3199mk4/POWER"
    state_topic: "tele/danieletest3199mk4/STATE"
    state_value_template: "{{ value_json.POWER }}"
    availability_topic: "tele/danieletest3199mk4/LWT"
    brightness_command_topic: "cmnd/danieletest3199mk4/Dimmer"
    brightness_state_topic: "tele/danieletest3199mk4/STATE"
    brightness_scale: 100
    on_command_type: "brightness"
    brightness_value_template: "{{ value_json.Dimmer }}"
    color_temp_command_topic: "cmnd/danieletest3199mk4/CT"
    color_temp_state_topic: "tele/danieletest3199mk4/STATE"
    color_temp_value_template: "{{ value_json.CT }}"
    rgb_command_topic: "cmnd/danieletest3199mk4/Color2"
    rgb_state_topic: "tele/danieletest3199mk4/STATE"
    rgb_value_template: "{{ value_json.Color.split(',')[0:3]|join(',') }}"
    effect_command_topic: "cmnd/danieletest3199mk4/Scheme"
    effect_state_topic: "tele/danieletest3199mk4/STATE"
    effect_value_template: "{{ value_json.Scheme }}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 0
    retain: false

sensor:
  - platform: mqtt
    name: "Pump Sensor"
    state_topic: "hometest/test321/test"
    unit_of_measurement: 'mA'
  - platform: mqtt
    name: "Voltage"
    state_topic: "cmnd/test321/v"
    unit_of_measurement: 'V'
  - platform: mqtt
    name: "Frequency"
    state_topic: "cmnd/test321/hz"
    unit_of_measurement: 'Hz'
  - platform: mqtt
    name: "Current"
    state_topic: "cmnd/test321/a"
    unit_of_measurement: 'A'
  - platform: mqtt
    name: "Power"
    state_topic: "cmnd/test321/w"
    unit_of_measurement: 'W'
  - platform: mqtt
    name: "Power Factor"
    state_topic: "cmnd/test321/pf"
  - platform: mqtt
    name: "Energy"
    state_topic: "cmnd/test321/wh"
    unit_of_measurement: 'Wh'

camera:
  - platform: foscam
    ip: mujacasa.ddns.net
    port: 89
    username: admin
    password: xxx
